notallowed = {
        [432] = true, [538] = true, [569] = true, 
        [590] = true, [537] = true, [449] = true
}
spaces = {
        ["Police Maverick"] = true, 
        ["Mountain Bike"] = true, 
        ["Pizza Boy"] = true,
        ["Utility Van"] = true, 
        ["Police Car (Los Santos)"] = true,
        ["Police Car (San Fierro)"] = true,
        ["Police Ranger"] = true,
        ["FBI Rancher"] = true, 
        ["FBI Truck"] = true,
        ["Fire Truck"] = true, 
        ["Fire Truck (Ladder)"] = true,
        ["Police Car (Las Venturas)"] = true,
        ["Black Boxville"] = true,
        ["Linerunner (From 'Tanker Commando')"] = true, 
        ["Mr. Whoopee"] = true,
        ["Cement Truck"] = true, 
        ["Combine Harvester"] = true, 
        ["Berkley's RC Van"] = true,
        ["Damaged Sadler"] = true,
        ["News Van"] = true, 
        ["RC Bandit"] = true,
        ["RC Baron"] = true, 
        ["RC Goblin"] = true,
        ["RC Raider"] = true,
        ["RC Tiger"] = true,
        ["BF Injection"] = true, 
        ["Bloodring Banger"] = true,
        ["Monster 2"] = true,
        ["Super GT"] = true, 
        ["Hotring Racer"] = true,
        ["Hotring Racer 2"] = true, 
        ["Hotring Racer 3"] = true, ["Rancher (From 'Lure')"] = true,
        ["RC Cam (flower pot)"] = true, 
        ["News Chopper"] = true
}